CREATE TABLE LEASING
(
  ID          BIGINT(20) NOT NULL AUTO_INCREMENT,
  HOUSING_ID  BIGINT(20),
  PERSON_ID   BIGINT(20),
  ASSIGN_DATE DATETIME,
  MONTHS      INT,

  PRIMARY KEY (ID)
)
  ENGINE = INNODB
  DEFAULT CHARSET = UTF8;