CREATE TABLE HISTORY
(
  ID          BIGINT(20) NOT NULL AUTO_INCREMENT,
  HOUSING_ID  BIGINT(20),
  NAME        VARCHAR(100),
  DESCRIPTION VARCHAR(200),

  PRIMARY KEY (ID)
)
  ENGINE = INNODB
  DEFAULT CHARSET = UTF8;