CREATE TABLE ACCOMMODATION
(
  ID           BIGINT(20) NOT NULL AUTO_INCREMENT,
  HOUSING_ID   BIGINT(20),
  PERSON_ID    BIGINT(20),
  SINGLE_OWNED BIT,
  START_DATE   DATETIME,
  END_DATE     DATETIME,

  PRIMARY KEY (ID)
)
  ENGINE = INNODB
  DEFAULT CHARSET = UTF8;