CREATE TABLE PERSON
(
  ID         BIGINT(20) NOT NULL AUTO_INCREMENT,
  FIRST_NAME VARCHAR(100),
  LAST_NAME  VARCHAR(100),
  FULL_NAME  VARCHAR(200),
  EMAIL      VARCHAR(100),
  PHONE      VARCHAR(50),

  PRIMARY KEY (ID),
  UNIQUE KEY NAME (FULL_NAME)
)
  ENGINE = INNODB
  DEFAULT CHARSET = UTF8;

CREATE TABLE ACCOUNT
(
  ID             BIGINT(20) NOT NULL AUTO_INCREMENT,
  PERSON_ID      BIGINT(20),
  LOGIN_NAME     VARCHAR(100),
  LOGIN_PASSWORD VARCHAR(100),

  PRIMARY KEY (ID),
  UNIQUE KEY NAME (LOGIN_NAME),
  CONSTRAINT FOREIGN KEY (PERSON_ID) REFERENCES PERSON (ID)
)
  ENGINE = INNODB
  DEFAULT CHARSET = UTF8;

CREATE TABLE HOUSING
(
  ID             BIGINT(20) NOT NULL AUTO_INCREMENT,
  ACCOUNT_ID     BIGINT(20),
  NAME           VARCHAR(100),
  ADDRESS_LINE_1 VARCHAR(100),
  ADDRESS_LINE_2 VARCHAR(50),
  CITY           VARCHAR(100),
  STATE          VARCHAR(2),
  ZIP5           VARCHAR(5),
  ACTIVE         BIT(1)     NOT NULL DEFAULT B'1',

  PRIMARY KEY (ID),
  UNIQUE KEY NAME (NAME),
  CONSTRAINT FOREIGN KEY (ACCOUNT_ID) REFERENCES ACCOUNT (ID)
)
  ENGINE = INNODB
  DEFAULT CHARSET = UTF8;